### PR TITLE
Attempt osx_arm64 build

### PR DESCRIPTION
**Pull request by rly**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rly** [comment]
@conda-forge-admin, please rerender

**Comment by rly** [comment]
I'm a novice at conda-forge packaging, so I don't know if this will work, but I think maybe it will?

**Comment by rly** [comment]
@conda-forge-admin, please rerender

**Comment by rly** [comment]
Alternatively we could try to make this a noarch with a windows-only dependency following the instructions here https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-builds

**Comment by rly** [comment]
@conda-forge-admin, please rerender

**Comment by yarikoptic** [comment]
@conda-forge-admin, please rerender

**Comment by rly** [comment]
@yarikoptic should I just create a fresh PR? I bet there would not be conflicts then.

**Comment by rly** [comment]
Replaced by #23.

**Pull request closed without merging**
